name: CI
on:
  push:
    branches:
      - main
      - feat/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: asnowc/actions@setup-node/v2
        with:
          node_v: 20
          pnpm_v: 9
          run_install: true
      - name: Test
        run: pnpm ci:test
