name: Publish
on:
  push:
    tags:
      - v*

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    if: ${{github.repository_owner == 'asnowc'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v2
        with:
          version: ^12.0.0
          runtime: node@22
          cache: true
      - name: Build
        run: pnpm run ci:build
      - name: Check Api
        run: pnpm run api:check
      - name: Publish-Jsr dry-run
        run: npx jsr publish --dry-run
      - name: Publish
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish-Jsr
        run: npx jsr publish
